// <auto-generated />
namespace AzureCodeCamp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class VideoTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VideoTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201303051332246_VideoTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
